services:
  python-app:
    build:
      context: .
    volumes:
      - .:/parser
    working_dir: /parser
    command: python main.py

  fastapi-app:
    build:
      context: .
    volumes:
      - .:/parser
    working_dir: /parser/
    ports:
        - "8001:8001"
    command: uvicorn api.app:app --host 0.0.0.0 --port 8001 --reload
