services:
  python-app:
    build:
      context: .
    volumes:
      - .:/parser
    working_dir: /parser
    command: python main.py

  fastapi-app:
    build:
      context: .
    volumes:
      - .:/parser
    working_dir: /parser/
    ports:
      - "8001:8000"
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000 --reload